* Doom Common Lisp

This project is an implementation of Doom data structures and
algorithms (but not graphics or gameplay) in Common Lisp as a learning
purpose. The ultimate goal is to have:

+ IWAD and PWAD file read
+ Read and modify levels
+ Have levels in memory
+ Be able to work with the levels in memory with an API
+ Expose the data so another rendering engine can be used
+ Not sure: Display level maps and be able to build new maps with an API?
+ Learn Common Lisp

* Why Common Lisp?

I've been a fan of Doom for years and I always wanted to learn proper
Common Lisp, after I started reading Paul Graham's On Lisp
(http://www.paulgraham.com/onlisp.html) I started to fall in love with
Common Lisp promises and I wanted to use its capabilities to really
learn to program. Actually I started reading Let Over Lambda first
(http://letoverlambda.com/) which brought me to a state of epiphany
after so many years of being a programmer.

* Project Milestones

The first milestone will be to be able to read a WAD file from Common
Lisp, and to be able to check its elements. I will write a Common Lisp
program that will be able to read a WAD file, and store in memory its
contents.

** Milestone 1

Being able to read a wad file:

+ [DONE] Correctly identify a file as a wad file (check header)
+ [DONE] Read wad file directory
+ [DONE] Read wad file MAP lump
+ [TODO] Read map structure

** Milestone 2

Do milestone 1 properly. I'm going to start defining some kind of
API. I'm not a Common Lisp expert (this is a project to learn), so my
API might be a bit imperative at first.

#+BEGIN_SRC lisp
  ;; Following line will read the doom2 wad file and bound
  ;; its result to the `iwad` object.
  (setf iwad (read-wad-file "doom2.wad"))
#+END_SRC

Ok so the `iwad' object will store information about a given IWAD file
and everything we get in this documentation:
https://zdoom.org/wiki/WAD should be reachable. Well, not everything,
but anything necessary to put some logic in the game (but not
rendering).

Ok, so next step: accesors. I want to use some kind of object oriented
syntax to access the elements of `iwad` object, like in the following
example:

#+BEGIN_SRC lisp
;; next line returns a list of maps
(slot-value iwad 'maps)
#+END_SRC

Each map could be a closure that can return its internal state
somehow:

#+BEGIN_SRC lisp
  ;; get list of all maps
  (setf maps (slot-value iwad 'maps))

  ;; get map01... it this OO syntax ok? should I use
  ;; a property list instead?
  (setf map01 (slot-value maps 'map01))

  ;; the property list syntax will look like:
  (getf maps :map01)
  ;; and it makes sense with lumps having unique names.
#+END_SRC

That's what I'm going to use, a property list to get the lumps (and
the aggregation lumps) from the map. A map is going to be a plist
also, this time it will store the different lumps of the map
(vertexes, nodes, sidedefs, etc.)

#+BEGIN_SRC lisp
  ;; should I also change this to a property list instead
  ;; of an object?
  (setf maps (slot-value iwad 'maps))

  ;; will store the map01 aggregation lump in `map01'
  (setf map01 (getf maps :map01))

  ;; how do I access the lumps inside this `map01' object?
  (getf map01 :things)
  ((:x 10 :y 20 :angle 90 :type 1 :flags 0)
   (:x 20 :y 30 :angle 90 :type 2 :flags 0))

#+END_SRC

This way, and considering the wad file structure, the sub lumps for a
lump, will be accessed by using plist semantics.

** Ok, back at the basics. What's a WAD

A WAD file is a collection of lumps. A lump is something that
identifies an object or entity in Doom. Enemies, sprites, sounds,
items, maps and textures are lumps. These lumps can be grouped
together. A familiar example of this grouping is a map. A Doom map is
a collection of lumps with some related sense: Physical construction
of the map (walls, windows and doors) and entities living in there:
demons, items and keys.

*** WAD Map Structure

Reference: http://www.gamers.org/dEngine/doom/spec/uds.1666.txt

The WAD file structure is very simple (it was meant for a game written
25 years ago). It has the following parts:

**** Header

The WAD file header is 12 bytes, it includes the following elements:

+ identifier: 4-bytes (chars). "PWAD" or "IWAD".
+ number-of-lumps: 4-bytes. Number of lumps in this file.
+ directory-offset: 4-bytes. Where do the file contents really or
  "Start of directory"

**** Lump Section

Bulk lump data. You'll need the "directory" to know where every lump
starts and ends.

**** Directory

The directory contains pointers to every lump in the lump section,
with its name. Each entry (16 byte) in the directory has the following
format:

+ Start of lump: 4-byte. File offset of start of lump
+ Size of lump: 4-byte. Size in bytes of lump
+ 8-byte ASCII string: Name of the lump

Up to the end of the file.

*** WAD File Reading Process

So the whole process would be the following:

1. Read the header:
   + Read the identifier
   + Read amount of lumps
   + Read directory offset
2. Go to the directory
   + Read 16 bytes
   + 4-bytes -> file offset with start of lump
   + 4-bytes -> lump size in bytes
   + 4-bytes -> name of lump
3. For every lump in point 2
   + Go to file offset
   + Read amount of bytes
   + Parse lump depending on type
